/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as VideoVideoIdRouteImport } from './routes/video.$videoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoVideoIdRoute = VideoVideoIdRouteImport.update({
  id: '/video/$videoId',
  path: '/video/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notifications': typeof NotificationsRoute
  '/ranking': typeof RankingRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/u/$username': typeof UUsernameRoute
  '/video/$videoId': typeof VideoVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notifications': typeof NotificationsRoute
  '/ranking': typeof RankingRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/u/$username': typeof UUsernameRoute
  '/video/$videoId': typeof VideoVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notifications': typeof NotificationsRoute
  '/ranking': typeof RankingRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/u/$username': typeof UUsernameRoute
  '/video/$videoId': typeof VideoVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/notifications'
    | '/ranking'
    | '/saved'
    | '/search'
    | '/upload'
    | '/u/$username'
    | '/video/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/notifications'
    | '/ranking'
    | '/saved'
    | '/search'
    | '/upload'
    | '/u/$username'
    | '/video/$videoId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/notifications'
    | '/ranking'
    | '/saved'
    | '/search'
    | '/upload'
    | '/u/$username'
    | '/video/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  NotificationsRoute: typeof NotificationsRoute
  RankingRoute: typeof RankingRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  UploadRoute: typeof UploadRoute
  UUsernameRoute: typeof UUsernameRoute
  VideoVideoIdRoute: typeof VideoVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$videoId': {
      id: '/video/$videoId'
      path: '/video/$videoId'
      fullPath: '/video/$videoId'
      preLoaderRoute: typeof VideoVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  NotificationsRoute: NotificationsRoute,
  RankingRoute: RankingRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  UploadRoute: UploadRoute,
  UUsernameRoute: UUsernameRoute,
  VideoVideoIdRoute: VideoVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
