/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as MessagesUsernameRouteImport } from './routes/messages.$username'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as VideoVideoIdRouteImport } from './routes/video.$videoId'
import { Route as YoutubeVideoIdRouteImport } from './routes/youtube.$videoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesUsernameRoute = MessagesUsernameRouteImport.update({
  id: '/messages/$username',
  path: '/messages/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoVideoIdRoute = VideoVideoIdRouteImport.update({
  id: '/video/$videoId',
  path: '/video/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeVideoIdRoute = YoutubeVideoIdRouteImport.update({
  id: '/youtube/$videoId',
  path: '/youtube/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/notifications': typeof NotificationsRoute
  '/ranking': typeof RankingRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/u/$username': typeof UUsernameRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/youtube/$videoId': typeof YoutubeVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/notifications': typeof NotificationsRoute
  '/ranking': typeof RankingRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/u/$username': typeof UUsernameRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/youtube/$videoId': typeof YoutubeVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/notifications': typeof NotificationsRoute
  '/ranking': typeof RankingRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/u/$username': typeof UUsernameRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/youtube/$videoId': typeof YoutubeVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/friends'
    | '/notifications'
    | '/ranking'
    | '/saved'
    | '/search'
    | '/terms'
    | '/upload'
    | '/messages/$username'
    | '/u/$username'
    | '/video/$videoId'
    | '/youtube/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/friends'
    | '/notifications'
    | '/ranking'
    | '/saved'
    | '/search'
    | '/terms'
    | '/upload'
    | '/messages/$username'
    | '/u/$username'
    | '/video/$videoId'
    | '/youtube/$videoId'
  id:
    | '__root__'
    | '/'
    | '/admin-login'
    | '/auth'
    | '/friends'
    | '/notifications'
    | '/ranking'
    | '/saved'
    | '/search'
    | '/terms'
    | '/upload'
    | '/messages/$username'
    | '/u/$username'
    | '/video/$videoId'
    | '/youtube/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  FriendsRoute: typeof FriendsRoute
  NotificationsRoute: typeof NotificationsRoute
  RankingRoute: typeof RankingRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  UploadRoute: typeof UploadRoute
  MessagesUsernameRoute: typeof MessagesUsernameRoute
  UUsernameRoute: typeof UUsernameRoute
  VideoVideoIdRoute: typeof VideoVideoIdRoute
  YoutubeVideoIdRoute: typeof YoutubeVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof NotificationsRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$username': {
      id: '/messages/$username'
      path: '/messages/$username'
      fullPath: '/messages/$username'
      preLoaderRoute: typeof MessagesUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$videoId': {
      id: '/video/$videoId'
      path: '/video/$videoId'
      fullPath: '/video/$videoId'
      preLoaderRoute: typeof VideoVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/$videoId': {
      id: '/youtube/$videoId'
      path: '/youtube/$videoId'
      fullPath: '/youtube/$videoId'
      preLoaderRoute: typeof YoutubeVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  FriendsRoute: FriendsRoute,
  NotificationsRoute: NotificationsRoute,
  RankingRoute: RankingRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  UploadRoute: UploadRoute,
  MessagesUsernameRoute: MessagesUsernameRoute,
  UUsernameRoute: UUsernameRoute,
  VideoVideoIdRoute: VideoVideoIdRoute,
  YoutubeVideoIdRoute: YoutubeVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
